os:
 - linux
language: go
before_install:
- sudo apt-get install libzmq3-dev
install:
- wget http://download.nanomsg.org/nanomsg-0.4-beta.tar.gz
- tar -xzvf nanomsg-0.4-beta.tar.gz
- cd nanomsg-0.4-beta
- ./configure && make && sudo make install && cd .. && sudo ldconfig
- go get github.com/tools/godep
- go get code.google.com/p/go.tools/cmd/cover
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega
- go install github.com/onsi/ginkgo/ginkgo
- go install github.com/onsi/gomega
- export PATH=$PATH:$HOME/gopath/bin
- $HOME/gopath/bin/godep restore
- go install -tags 'nano zmq' github.com/CapillarySoftware/goiostat
script: $HOME/gopath/bin/ginkgo -cover -r --race
deploy:
  provider: releases
  api_key:
    secure: cAfvm2u93f2+NVWn0KOVgjQKl/ZiRO579l+2hm0BN3A+0ptgNuY2wxonhpfy5S5j9cVohm6XyaEdD+TYPQJXm1XVCb7PvPCHdgk833pgBZd79lKy+N/Uz2fd9V3Al3Y/57+eP4V263Z+8/YYDttrqB1NOQ7cX2xAV4Ql3tf2hY4=
  file: $HOME/gopath/bin/goiostat
  skip_cleanup: true
  on:
    repo: CapillarySoftware/goiostat
    tags: true
    all_branches: true
