language: go

build_deps:
  pkg.installed:
    - pkgs:
      - git
      - g++
      - make
      - libzmq3-dev

install:
 - export GOPATH=`pwd`
 - export GOBIN=$GOPATH/bin
 - export PATH=$PATH:$GOBIN
 - go get github.com/dustin/go-humanize
 - go get github.com/onsi/gomega
 - go get github.com/onsi/ginkgo
 - go get code.google.com/p/go.tools/cmd/cover
 - go get code.google.com/p/goprotobuf/proto
 - go install github.com/onsi/ginkgo/ginkgo
 - go install github.com/onsi/gomega
 - go get github.com/pebbe/zmq4

script: bin/run_tests_travis.sh
